set(CSTOOLKIT_USE_GIT_TAG_VERSION ON)
set(CSTOOLKIT_CPACK_RULES ON)
set(CSTOOLKIT_DISABLE_COMMON_CPPRULES ON)
set(CSTOOLKIT_AUTO_DEPLOY_QT OFF)

set(CSTOOLKIT_DEFAULT_PUBLIC_HEADERS_DIRS "inc")
set(CSTOOLKIT_DEFAULT_SOURCES_DIRS "src")
set(CSTOOLKIT_DEFAULT_UI_DIRS "forms")
set(CSTOOLKIT_DEFAULT_RESOURCES_DIRS "resources")

# Fix '\' in path
file(TO_CMAKE_PATH "$ENV{CMAKE_REGISTRY}" cmake_registry_path)

set(CMAKE_INSTALL_PREFIX "${cmake_registry_path}/${CMAKE_PROJECT_NAME}")
list(APPEND CMAKE_PREFIX_PATH "${cmake_registry_path}")

include(${CMAKE_CURRENT_LIST_DIR}/CSToolkit.cmake)
