set(CSTOOLKIT_USE_GIT_TAG_VERSION ON)
set(CSTOOLKIT_CPACK_PACKAGE ON)
set(CSTOOLKIT_DISABLE_COMMON_CPPRULES ON)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

include(${CMAKE_CURRENT_LIST_DIR}/CSToolkit.cmake)
