set(CFMAKE_AUTO_FIND_PACKAGE ON)
set(CFMAKE_CHECK_DEPENDENCIES ON)

include(${CMAKE_CURRENT_LIST_DIR}/CFMake.cmake)

set(CMAKE_CXX_STANDARD 14)

if(CONAN)
    list(JOIN CONAN_RUNTIME_LIB_DIRS ":" CONAN_LD_LIBRARY_PATH)
    set(Qt5Widgets_UIC_EXECUTABLE ${CMAKE_COMMAND} -E env LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH}:${CONAN_LD_LIBRARY_PATH} -- $<TARGET_FILE:Qt5::uic>)
endif()
