if(NOT BUILD_VERSION STREQUAL "")
	set(CSTOOLKIT_PROJECT_VERSION ${BUILD_VERSION})
endif()

include(${CMAKE_CURRENT_LIST_DIR}/CSToolkit.cmake)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD 1)
set(CMAKE_INSTALL_MESSAGE LAZY)

# GCC configuration
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    add_compile_options(-Wpedantic)
endif()
