cd %~dp0/src
cd StreamWorkEditor2
call generatevcproj.bat
cd ../SwConfiguration
call generatevcproj.bat
cd ../SwCore
call generatevcproj.bat
cd ../SwDataBase
call generatevcproj.bat
cd ../SwDoc
call generatevcproj.bat
cd ../SwEditor
call generatevcproj.bat
cd ../SwExecution
call generatevcproj.bat
cd ../SwFoundation
call generatevcproj.bat
cd ../SwGenerator
call generatevcproj.bat
cd ../SwGui
call generatevcproj.bat
cd ../SwLauncher
call generatevcproj.bat
cd ../SwModel2
call generatevcproj.bat
cd ../SwRecord
call generatevcproj.bat
cd ../SwService
cd ServiceConfiguration
call generatevcproj.bat
cd ../ServiceMainWindow
call generatevcproj.bat
cd ../ServiceShortcut
call generatevcproj.bat
cd ../ServiceTools
call generatevcproj.bat
cd ../../../