################################################################################
# Package definition
################################################################################

function(define_package)

  # Check sub-project

  if(NOT PROJECT_NAME STREQUAL CMAKE_PROJECT_NAME)
    return()
  endif(NOT PROJECT_NAME STREQUAL CMAKE_PROJECT_NAME)

  # Restriction alias

  if(ENABLE_NATO_RESTRICTION OR ENABLE_ITAR_RESTRICTION)
    string(APPEND PACKAGE_RESTRICTION_ALIAS ".")
    if(ENABLE_NATO_RESTRICTION)
      string(APPEND PACKAGE_RESTRICTION_ALIAS "n")
    endif(ENABLE_NATO_RESTRICTION)
    if(ENABLE_ITAR_RESTRICTION)
      string(APPEND PACKAGE_RESTRICTION_ALIAS "i")
    endif(ENABLE_ITAR_RESTRICTION)
  endif(ENABLE_NATO_RESTRICTION OR ENABLE_ITAR_RESTRICTION)

  # Package configuration

  set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
  set(CPACK_PACKAGE_VENDOR "CS GROUP")
  set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
  set(CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_PROJECT_VERSION_MAJOR})
  set(CPACK_PACKAGE_VERSION_MINOR ${CMAKE_PROJECT_VERSION_MINOR})
  set(CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PROJECT_VERSION_PATCH})

  if(CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x64")
    set(CPACK_SYSTEM_NAME "win64")
  else(CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x64")
    set(CPACK_SYSTEM_NAME "win32")
  endif(CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x64")

  set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}${PACKAGE_RESTRICTION_ALIAS}.${CPACK_PACKAGE_VERSION}.${CPACK_SYSTEM_NAME}_Setup")

  if(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "DIGINEXT\\\\${CMAKE_PROJECT_NAME}${PACKAGE_RESTRICTION_ALIAS}.${CPACK_PACKAGE_VERSION}.${CPACK_SYSTEM_NAME}")
  else(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "DIGINEXT\\\\${CPACK_PACKAGE_INSTALL_DIRECTORY_NAME}")
  endif(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)

  # License

  set(CPACK_PACKAGE_ICON "${CMAKE_MODULE_LICENSE_PATH}/\\\\CS_GROUP_Logo.bmp")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_MODULE_LICENSE_PATH}/CS_GROUP_EULA.rtf")
  install(FILES "${CMAKE_MODULE_LICENSE_PATH}/CS_GROUP_EULA.pdf" DESTINATION ".")

  # VCRedist

  string(REPLACE "-" "_" VCREDIST_COMPONENT_NAME ${TARGET_NAME})
  install(FILES ${VCRedist_ROOT}/vc_redist.${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}.exe DESTINATION "." COMPONENT ${VCREDIST_COMPONENT_NAME})
  list(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "ExecWait \\\"$INSTDIR\\\\vc_redist.${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}.exe /install /passive /norestart\\\"")

  # HASP for GEMALTO RTE

  set(HASP_COMPONENT_NAME "GEMALTO_RTE")
  install(FILES ${HASP_ROOT}/hasp_rt.exe DESTINATION "." COMPONENT ${HASP_COMPONENT_NAME})
  install(FILES ${HASP_ROOT}/haspdinst.exe DESTINATION "." COMPONENT ${HASP_COMPONENT_NAME})
  list(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "ExecWait \\\"$INSTDIR\\\\haspdinst.exe -i -criticalmsg\\\"")

  # Install and uninstall commands + create and delete icons

  string(REPLACE ";" "\n" CPACK_NSIS_EXTRA_INSTALL_COMMANDS "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}")
  string(REPLACE ";" "\n" CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "${CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS}")
  string(REPLACE ";" "\n" CPACK_NSIS_CREATE_ICONS_EXTRA "${CPACK_NSIS_CREATE_ICONS_EXTRA}")
  string(REPLACE ";" "\n" CPACK_NSIS_DELETE_ICONS_EXTRA "${CPACK_NSIS_DELETE_ICONS_EXTRA}")

  # Package configuration

  include(InstallRequiredSystemLibraries)
  include(CPack)

endfunction(define_package)
