################################################################################
# Package definition
################################################################################

function(define_package)

  # Check sub-project

  if(NOT PROJECT_NAME STREQUAL CMAKE_PROJECT_NAME)
    return()
  endif(NOT PROJECT_NAME STREQUAL CMAKE_PROJECT_NAME)

  # Restriction alias

  if(ENABLE_NATO_RESTRICTION)
    string(APPEND PACKAGE_RESTRICTION_ALIAS "n${NATO_IDENTIFIER}")
  endif(ENABLE_NATO_RESTRICTION)

  if(ENABLE_ITAR_RESTRICTION)
    if(PACKAGE_RESTRICTION_ALIAS)
      string(APPEND PACKAGE_RESTRICTION_ALIAS ".")
    endif(PACKAGE_RESTRICTION_ALIAS)
    string(APPEND PACKAGE_RESTRICTION_ALIAS "i${ITAR_IDENTIFIER}")
  endif(ENABLE_ITAR_RESTRICTION)

  if(ENABLE_SPECIAL_RESTRICTION)
    if(PACKAGE_RESTRICTION_ALIAS)
      string(APPEND PACKAGE_RESTRICTION_ALIAS ".")
    endif(PACKAGE_RESTRICTION_ALIAS)
    string(APPEND PACKAGE_RESTRICTION_ALIAS "s${SPECIAL_IDENTIFIER}")
  endif(ENABLE_SPECIAL_RESTRICTION)

  if(PACKAGE_RESTRICTION_ALIAS)
    set(PACKAGE_RESTRICTION_ALIAS "_${PACKAGE_RESTRICTION_ALIAS}")
  endif(PACKAGE_RESTRICTION_ALIAS)

  # Package configuration

  set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
  set(CPACK_PACKAGE_VENDOR "CS GROUP")
  set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
  set(CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_PROJECT_VERSION_MAJOR})
  set(CPACK_PACKAGE_VERSION_MINOR ${CMAKE_PROJECT_VERSION_MINOR})
  set(CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PROJECT_VERSION_PATCH})
  set(CPACK_SYSTEM_NAME ${CMAKE_CXX_COMPILER_ARCHITECTURE_ID})

  set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${CPACK_PACKAGE_VERSION}${PACKAGE_RESTRICTION_ALIAS}_${CPACK_SYSTEM_NAME}_Setup")

  if(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "DIGINEXT\\\\${CMAKE_PROJECT_NAME}_${CPACK_PACKAGE_VERSION}${PACKAGE_RESTRICTION_ALIAS}_${CPACK_SYSTEM_NAME}")
  else(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "DIGINEXT\\\\${CPACK_PACKAGE_INSTALL_DIRECTORY_NAME}")
  endif(NOT DEFINED CPACK_PACKAGE_INSTALL_DIRECTORY_NAME)

  # Package properties

  set(PACKAGE_PROPERTIES_IN ${CMAKE_MODULE_TEMPLATES_PATH}/PackageProperties.md.in)
  set(PACKAGE_PROPERTIES_OUT ${CMAKE_CURRENT_BINARY_DIR}/PackageProperties.md)
  configure_file(${PACKAGE_PROPERTIES_IN} ${PACKAGE_PROPERTIES_OUT} @ONLY)
  install(FILES "${CMAKE_CURRENT_BINARY_DIR}/PackageProperties.md" DESTINATION "." RENAME "About.txt")

  # License

  set(CPACK_PACKAGE_ICON "${CMAKE_MODULE_LICENSE_PATH}/\\\\CS_GROUP_Logo.bmp")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_MODULE_LICENSE_PATH}/CS_GROUP_EULA.rtf")
  install(FILES "${CMAKE_MODULE_LICENSE_PATH}/CS_GROUP_EULA.pdf" DESTINATION ".")

  # VisualRedistributable

  set(VISUALREDISTRIBUTABLE_COMPONENT_NAME "VisualRedistributable")
  install(FILES ${VCRedist_ROOT}/vc_redist.${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}.exe DESTINATION "." COMPONENT ${VISUALREDISTRIBUTABLE_COMPONENT_NAME})
  list(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "ExecWait \\\"$INSTDIR\\\\vc_redist.${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}.exe /install /passive /norestart\\\"")

  # LicenseManager

  set(LICENSEMANAGER_COMPONENT_NAME "LicenseManager")
  install(FILES ${HASP_ROOT}/hasp_rt.exe DESTINATION "." COMPONENT ${LICENSEMANAGER_COMPONENT_NAME})
  install(FILES ${HASP_ROOT}/haspdinst.exe DESTINATION "." COMPONENT ${LICENSEMANAGER_COMPONENT_NAME})
  list(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "ExecWait \\\"$INSTDIR\\\\haspdinst.exe -i -criticalmsg\\\"")

  # Install and uninstall commands + create and delete icons

  string(REPLACE ";" "\n" CPACK_NSIS_EXTRA_INSTALL_COMMANDS "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}")
  string(REPLACE ";" "\n" CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "${CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS}")
  string(REPLACE ";" "\n" CPACK_NSIS_CREATE_ICONS_EXTRA "${CPACK_NSIS_CREATE_ICONS_EXTRA}")
  string(REPLACE ";" "\n" CPACK_NSIS_DELETE_ICONS_EXTRA "${CPACK_NSIS_DELETE_ICONS_EXTRA}")

  # Package configuration

  get_cmake_property(CPACK_COMPONENTS_ALL COMPONENTS)
  list(REMOVE_ITEM CPACK_COMPONENTS_ALL "Debugging")

  # include(InstallRequiredSystemLibraries)
  include(CPack)

endfunction(define_package)
