# This is called after the call to project()
set(PACKAGE_VERSION 0.0.0.0 CACHE STRING "Version of the package, will set CMAKE_PROJECT_VERSION and PROJECT_VERSION")

set(CMAKE_PROJECT_VERSION ${PACKAGE_VERSION} CACHE INTERNAL "...")
set(PROJECT_VERSION ${PACKAGE_VERSION})
set(${PROJECT_NAME}_VERSION ${PACKAGE_VERSION})

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/install" CACHE PATH "Project installation path" FORCE)
endif()

set(_WINDOWS_KITS_LIB_DIR "C:/Program Files (x86)/Windows Kits/10/Lib/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}/um/x64")
message("_WINDOWS_KITS_LIB_DIR ${_WINDOWS_KITS_LIB_DIR}")

include(Qt)
