set(SOLUTION_VERSION 0.0.0.0 CACHE STRING "Version of the solution, will set CMAKE_PROJECT_VERSION and PROJECT_VERSION")

set(CMAKE_PROJECT_VERSION ${SOLUTION_VERSION} CACHE INTERNAL "...")
set(PROJECT_VERSION ${SOLUTION_VERSION})
set(${PROJECT_NAME}_VERSION ${SOLUTION_VERSION})