# -- TO REMOVE: deprecated rules skip Boost compiler settings -- #
!deprecated_rules {
# -- TO REMOVE: deprecated rules skip Boost compiler settings -- #


boost: \
build_pass( binary ) {

    # -- Unsupported environments -- #

    winrt:              qserror( "Boost not supported for Windows Runtime platforms" )
    else: mac:          qserror( "Boost not supported for Darwin-based platforms" )
    else: android:      qserror( "Boost not supported for Android platforms" )
    else: linux:        qserror( "Boost not supported for Linux-based platforms" )
    else: win32: !msvc: qserror( "Boost requires Windows MSVC compiler" )


    # -- Boost variables check -- #

    isEmpty( BOOST_ROOT ): \
        qserror( "BOOST_ROOT variable must be defined" )

    else: isEmpty( BOOST_VERSION ): \
        qserror( "Boost version cannot be resolved" )

    else: !exists( $${BOOST_INCLUDEDIR} ): \
        qserror( "Boost $${BOOST_VERSION} include path '$${BOOST_INCLUDEDIR}' not found" )

    else: !isEmpty( BOOST ) {

        !exists( $${BOOST_LIBRARYDIR} ): \
            qserror( "Boost $${BOOST_VERSION} library path '$${BOOST_LIBRARYDIR}' not found" )

        BOOST.CONFIG = shared $${BOOST.CONFIG}
        BOOST.CONFIG = $$remove( BOOST.CONFIG, ^(?!static$|shared$|combined$).*$ )
        BOOST.CONFIG = $$last( BOOST.CONFIG )
    }


    # -- Windows 32/64 bits MSVC environment -- #

    win32 {

        ## C++ preprocessor macros definition

        DEFINES *= BOOST_ALL_NO_LIB         # disables autolinking functionality

        ## Include directory registration

        INCLUDEPATH *= $$clean_path( $${BOOST_INCLUDEDIR} )

        ## Linker entries registration

        for( module, BOOST ) {

            library = boost_$$lower( $${module} )-$${BOOST_LIBS_SUFFIX}
            contains( BOOST.CONFIG, static|combined ): library = lib$${library}

            add_library( $${BOOST.CONFIG}, $${BOOST_LIBRARYDIR}, $${library} )
        }
    }
}


}
