# -- Visual C++ projects definition -- #
#    by default: set to $${TARGET}[.$${TOOLKIT.mkspec}]

msvc-proj {

    QMAKE_PROJECT_NAME = $$TARGET()

    mkspec_makefile {

        QMAKE_PROJECT_NAME = $${QMAKE_PROJECT_NAME}.$${TOOLKIT.mkspec}
        TEMPLATE( subdirs ): TARGET = $${TARGET}.$${TOOLKIT.mkspec}
    }
}


# -- Makefile-based project definition -- #
#    by default: set to Makefile[.$${TOOLKIT.mkspec}]

else {

    MAKEFILE = Makefile

    mkspec_makefile: \
        MAKEFILE = $${MAKEFILE}.$${TOOLKIT.mkspec}

    # for subdirs-based project: set subprojects makefiles to makefile name

    TEMPLATE( subdirs ) {

        for( subdir, SUBDIRS ): \
            eval( $${subdir}.makefile = $${MAKEFILE} )
    }
}
