# -- Target features configuration -- #

!TEMPLATE( lib ) {

    CONFIG -= static_and_shared \           # makes sure that non-library project doesn't have static_and_shared option
              static_or_shared

    TEMPLATE( subdirs ) {

        msvc-proj: \                        # force directories listed to be processed in the order in which they are given (Visual C++ projects only)
        qtLessThan( 5.4, true ): \          # this feature is no more required from Qt 5.4.1, as SUBDIRS .depends modifier is supported
            CONFIG *= ordered

        CONFIG *= no_empty_targets          # makes sure that subdirs-based project doesn't have targets that do nothing
    }
}

win32 {

    TEMPLATE( app ) {

        QT( gui )|!console: \
            CONFIG = windows $${CONFIG}     # identifies target as a Windows windowed application if Qt gui module detected or console mode not specified
    }

    CONFIG *= skip_target_version_ext       # removes version number on target file name
}

else: linux {

    TEMPLATE( binary ) {

        QT( gui ): CONFIG *= x11            # identifies target as a X11 application or library
        else:      CONFIG -= x11

        TEMPLATE( shared ): \
            CONFIG -= lib_version_first     # makes sure that version number on shared library target file name is suffixed
    }
}


# -- Target extension definition -- #

isEmpty( TARGET_EXT ) {

    TEMPLATE( app ):              TARGET_EXT = $${QMAKE_EXT_APP}
    else {

        TEMPLATE( shared ):       TARGET_EXT = $${QMAKE_EXT_SHLIB}
        else: TEMPLATE( static ): TARGET_EXT = $${QMAKE_EXT_STATICLIB}
    }
}

!isEmpty( TARGET_EXT ) {

    !startsWith( TARGET_EXT, $$re_escape( . ) ): \
        TARGET_EXT = .$${TARGET_EXT}
}


# -- Target name definition -- #

!TEMPLATE( binary ) {                       # defines non-binary target without debug modifiers

    TARGET = $$TARGET()

    TEMPLATE( subdirs ): isEmpty( SUBDIRS ): \
        qswarning( "Empty SUBDIRS variable value detected" )
}

else {

    build_pass() {                          # else add optional debug modifiers in debug mode

        build_mode( release ):     TARGET = $$TARGET( release )
        else: build_mode( debug ): TARGET = $$TARGET( debug )
    }

    # during meta-target generation pass:
    # forces TARGET to target release name for Qt 4.7 compatibility
    else: TARGET = $$TARGET()
}
