# -- TO REMOVE: deprecated rules skip Visual C++ precompiled header rules -- #
!deprecated_rules {
# -- TO REMOVE: deprecated rules skip Visual C++ precompiled header rules -- #


msvc: build_pass( binary ) {

    # -- Visual C++ precompiled header -- #

    precompile_header: \
    !isEmpty( PRECOMPILED_HEADER ) {

        # Generates a precompiled header in generated/$${TOOLKIT.mkspec}/pch for:
        #   - Visual C++ projects: avoid duplicated pch source registration when using $$files() function
        #   - Visual C++ 12.0 and below: needed for utf8 feature management

        msvc-proj|lessThan( TOOLKIT.compiler.version, 2015 ) {

            PRECOMPILED_DIR = $$clean_path( generated/$${TOOLKIT.mkspec}/pch )

            _stdafx = $$relative_path( $$absolute_path( $${PRECOMPILED_HEADER}, $${_PRO_FILE_PWD_} ), $$absolute_path( $${PRECOMPILED_DIR}, $${_PRO_FILE_PWD_} ) )
            _stdafx = $$quote( $${LITERAL_HASH}include \"$${_stdafx}\" )

            PRECOMPILED_HEADER = $${PRECOMPILED_DIR}/stdafx.h
            write_file( $${_PRO_FILE_PWD_}/$${PRECOMPILED_HEADER}, _stdafx )

            unset( _stdafx )
        }
    }
}


}
