# -- Qt default configurations -- #
#    restores Qt configurations according to default qmake behaviour:
#      - adds project directory to include paths
#      - enables precompiled headers support for Windows platforms
#      - identifies target as a Windows windowed application if Qt gui module detected or console mode not specified
#    and harmonizes library target features

CONFIG -= no_include_pwd
win32: CONFIG *= precompile_header

win32: TEMPLATE( app ) {

    QT( gui )|!console: \
        CONFIG = windows $${CONFIG}
}

TEMPLATE( lib ) {

    TEMPLATE( static ): CONFIG *= static staticlib
    else:               CONFIG *= shared dll dylib
}


# -- Deprecated rules detection -- #

qswarning( "Deprecated rules detected. '$$system_path( $${QSMAKEPATH} )' post features skipped" )
