# -- function: add_pseudo_var( variablename ) -- #

defineTest( add_pseudo_var ) {

    arg.variable = $${1}

    !isEmpty( arg.variable ) {

        _pseudo_vars *= $${arg.variable}
        export( _pseudo_vars )

        return( true )
    }

    return( false )
}

# -- function: remove_pseudo_var( variablename ) -- #

defineTest( remove_pseudo_var ) {

    arg.variable = $${1}

    contains( _pseudo_vars, $${arg.variable} ) {

        clear( $${arg.variable} )
        export( $${arg.variable} )

        _pseudo_vars -= $${arg.variable}
        export( _pseudo_vars )

        return( true )
    }

    return( false )
}

# -- function: clear_pseudo_vars() -- #

defineTest( clear_pseudo_vars ) {

    for( variable, _pseudo_vars ) {

        clear( $${variable} )
        export( $${variable} )
    }

    clear( _pseudo_vars )
    export( _pseudo_vars )

    return( true )
}


# -- function: resolve_pseudo_vars( [variablename] ) -- #
#    required qmake 3.0 (5.0) minimum to resolve all variables

defineReplace( resolve_pseudo_vars.substitute ) {

    ## variables substitution sub-routine

    arg.variable = $${1}
    string = $$eval( $${arg.variable} )

    variables = $$eval( _pseudo_vars )
    substituted = false

    for( variable, variables ): \
        find( string, $${variable} ) {

            value = $$eval( $${variable} )
            string = $$replace( string, $$re_escape( ${$${variable}} ), $${value} )
            substituted = true
        }

    equals( substituted, true ): \
        return( $${string} )

    return( )
}

defineTest( resolve_pseudo_vars ) {

    ## predefined variables resolution

    !isEmpty( ARGS ): \
        variables = $${1}

    else {

        qtLessThan( 5.0 ): \
            qswarning( "Pseudo variables resolution on any qmake variable not supported" )

        else {

            variables = $$enumerate_vars()
            variables -= _pseudo_vars
        }
    }

    ## predefined variables substitution

    for( variable, variables ) {

        value = $$resolve_pseudo_vars.substitute( $${variable} )

        !isEmpty( value ) {

            eval( $${variable} = $${value} )
            export( $${variable} )
        }
    }

    return( true )
}
