# -- Target build modes configuration -- #

# If debug or release CONFIG option is set in qmake arguments:
# debug_and_release option is disabled

debug_or_release: \
    CONFIG -= debug_and_release

# When using the debug_and_release option:
#   - debug and release builds end up in separate debug and release directories
#   - debug and release builds are disabled during meta pass
#   - target informations are not generated during meta pass
#   - debug_and_release related options are disabled during build pass

debug_and_release: \
    CONFIG *= debug_and_release_target

debug_and_release: !build_pass {

    CONFIG -= debug release
    CONFIG *= no_generated_target_info
}

else {

    CONFIG -= debug_and_release_target \
              build_all

    build_mode( release ):     CONFIG -= debug
    else: build_mode( debug ): CONFIG -= release
}


# If release with debug info mode is enabled:
#   - creates a separate debug informations file (Linux platform only)
#   - displays a log message

force_debug_info {

    build_mode( release ): \
        qsmessage( "Release with debug informations mode activated" )

    linux: CONFIG *= separate_debug_info
}


# -- Library build modes configuration -- #

TEMPLATE( lib ) {

    # If static, staticlib, shared, dll or dylib CONFIG option is set in qmake arguments:
    # static_and_shared option is disabled

    static_or_shared: \
        CONFIG -= static_and_shared

    # When using the static_and_shared option:
    #   - static and shared builds are disabled during meta pass
    #   - target informations are not generated during meta pass

    static_and_shared: !build_pass {

        CONFIG -= static staticlib
        CONFIG -= shared dll dylib
        CONFIG *= no_generated_target_info
    }

    # Otherwise:
    #   - defines plugin as shared library if library type not defined
    #   - harmonizes library target features

    else {

        plugin {

            !TEMPLATE( static ): \
                CONFIG *= shared
        }

        TEMPLATE( static ) {

            CONFIG *= static staticlib
            CONFIG -= shared dll dylib
        }

        else {

            CONFIG -= static staticlib
            CONFIG *= shared dll dylib
        }
    }
}


# -- Compilation warnings configuration -- #

!warn_on|warn_off {

    CONFIG -= warn_on
    CONFIG *= warn_off
}


# -- Compiler exception support -- #

!exceptions|exceptions_off {

    CONFIG -= exceptions
    CONFIG *= exceptions_off
}


# -- Compiler RTTI support -- #

!rtti|rtti_off {

    CONFIG -= rtti
    CONFIG *= rtti_off
}


# -- Compiler STL support -- #

!stl|stl_off {

    CONFIG -= stl
    CONFIG *= stl_off
}
