# -- TO REMOVE: deprecated rules skip target resources rules -- #
!deprecated_rules {
# -- TO REMOVE: deprecated rules skip target resources rules -- #


build_pass( binary ): \
!TEMPLATE( static ) {

    win32 {

        # -- qmake Windows resource file generation     -- #
        # -- (available on qmake 3.0 (Qt5.0) and later) -- #

        qtGreaterThan( 5.0, true ) {

            !isEmpty( RC_FILE )| \
            !isEmpty( RES_FILE ): \
                qsmessage( "Target informations generation skipped because of custom RC file detected" )

            else {

                !isEmpty( RC_ICONS ) {

                    !endsWith( RC_ICONS, $${QMAKE_EXT_ICO} ): \
                        RC_ICONS = $${RC_ICONS}$${QMAKE_EXT_ICO}                                            # specifies the icons that should be included into a generated .rc file
                }

                isEmpty( RC_LANG ): RC_LANG = 0x0409                                                        # set language to English(USA) if not defined
                isEmpty( RC_CODEPAGE ): RC_CODEPAGE = 1200                                                  # set codepage to Unicode UTF-16 if not defined

                QMAKE_TARGET_PRODUCT = $${PROPERTIES.product}                                               # specifies the product for the project target
                QMAKE_TARGET_DESCRIPTION = $${PROPERTIES.description}                                       # specifies the description for the project target
                QMAKE_TARGET_COMPANY = $${PROPERTIES.company}                                               # specifies the company for the project target
                QMAKE_TARGET_COPYRIGHT = $$replace( PROPERTIES.copyright, $$re_escape( "(C)" ), "\\251" )   # specifies the copyright information for the project target
            }
        }

        # -- verpatch Windows resource file generation    -- #
        # -- (available on qmake 2.01a (Qt4.8) and below) -- #

        else: !isEmpty( VERSION ) {

            isEmpty( RC_LANG ): RC_LANG = 0x0409                                                                                # set language to English(USA) if not defined

            _verpatch_args =  $$quote( "/va $${VER_MAJ}.$${VER_MIN}.$${VER_PAT}.$${VER_BLD}" )                                  # specifies the version for the project target
            _verpatch_args += $$quote( "/langid $${RC_LANG}" )                                                                  # specifies the language for the project target
            _verpatch_args += $$quote( "/pv $${VER_MAJ}.$${VER_MIN}.$${VER_PAT}.$${VER_BLD}" )
            _verpatch_args += $$quote( "/s CompanyName \"$${PROPERTIES.company}\"" )                                            # specifies the company for the project target
            _verpatch_args += $$quote( "/s FileDescription \"$${PROPERTIES.description}\"" )                                    # specifies the description for the project target
            _verpatch_args += $$quote( "/s LegalCopyright \"$$replace( PROPERTIES.copyright, $$re_escape( "(C)" ), "©" )\"" )   # specifies the copyright information for the project target
            _verpatch_args += $$quote( "/s ProductName \"$${PROPERTIES.product}\"" )                                            # specifies the product for the project target

            QMAKE_POST_LINK = $$quote( "$${QSMAKEPATH}/tools/verpatch.exe $${DESTDIR}/$${TARGET}$${TARGET_EXT} $${_verpatch_args}" ) $${QMAKE_POST_LINK}

            unset( _verpatch_args )
        }
    }
}


}
