# -- Target build modes configuration -- #
#    by default: target queries only processed in release mode

CONFIG -= debug_and_release
CONFIG *= release


# -- qmake processing configuration -- #
#    by default: disables project and target informations generation

CONFIG *= no_generate_project
CONFIG *= no_generated_target_info


# -- Target properties output -- #

assert( !isEmpty( QUERY_TARGET_PROPERTY ) )

equals( QUERY_TARGET_PROPERTY, template ) {

    _template = unknown

    TEMPLATE( pseudo ):       _template = pseudo
    else: TEMPLATE( binary ): _template = binary

    !equals( _template, unknown ) {

        TEMPLATE( aux|subdirs|app ): \
            _template += $${TEMPLATE}

        else {

            TEMPLATE( plugin ):    _template += plugin
            else: TEMPLATE( lib ): _template += lib
        }
    }

    contains( _template, lib|plugin ) {

        static_and_shared: \
            _template += static shared

        else {

            TEMPLATE( static ):       _template += static
            else: TEMPLATE( shared ): _template += shared
        }
    }

    log( "$$escape_expand( $${_template}\\n )" )
    unset( _template )
}

else: qserror( "Unknown '$${QUERY_TARGET_PROPERTY}' target property query" )
