# -- function: preprocessor.msvc() -- #

defineReplace( preprocessor.msvc ) {

    output = $$system( "$${QMAKE_CXX} -nologo -E \"$${PWD}/../templates/qs_macros.cpp\" <NUL 2>NUL", lines )
    isEmpty( output ): error( "Cannot run compiler '$${QMAKE_CXX}'. Maybe you forgot to setup the environment ?" )

    return( $${output} )
}

# -- function: preprocessor.gcc() -- #

defineReplace( preprocessor.gcc ) {

    equals( QMAKE_HOST.os, Windows ):     null_device = NUL
    else: equals( QMAKE_HOST.os, Linux ): null_device = /dev/null

    output = $$system( "$${QMAKE_CXX} -E \"$${PWD}/../templates/qs_macros.cpp\" <$${null_device} 2>$${null_device}", lines )
    isEmpty( output ): error( "Cannot run compiler '$${QMAKE_CXX}'. Maybe you forgot to setup the environment ?" )

    return( $${output} )
}


# -- Proprocessing macros generation                        -- #
# -- (available on Qt5.8 and later for Visual C++ projects) -- #

msvc: qtGreaterThan( 5.8, true ): _generated = $$preprocessor.msvc()
else: gcc: _generated = $$preprocessor.gcc()


# -- Proprocessing variables resolution -- #

qtLessThan( 5.0 ) {

    _generated = $$quote( $${_generated} )
    _generated = $$replace( _generated, $$escape_expand( \\r\\n ), $$escape_expand( \\n ) )
    _generated = $$split( _generated, $$escape_expand( \\n ) )
}

for( line, _generated ) {

    isEmpty( line )|startsWith( line, $${LITERAL_HASH} ): next()

    variable = $$remove( line, [ ].*$ )
    value = $$remove( line, ^.*=[ ]* )

    isEmpty( variable )|isEmpty( value ): \
        error( "Compiler '$${QMAKE_CXX}' produced empty invalid for $${line}." )

    eval( $${variable} = $${value} )
}

unset( _generated )
