# -- Target build modes configuration -- #
#    by default: toolkit queries only processed in release mode

CONFIG -= debug_and_release
CONFIG *= release


# -- qmake processing configuration -- #
#    by default: disables project and target informations generation

CONFIG *= no_generate_project
CONFIG *= no_generated_target_info


# -- Toolkit properties output -- #

assert( !isEmpty( QUERY_TOOLKIT_PROPERTY ) )

isEmpty( TOOLKIT.$${QUERY_TOOLKIT_PROPERTY} ): \
    qserror( "Unknown '$${QUERY_TOOLKIT_PROPERTY}' toolkit property query" )

log( "$$escape_expand( $$eval( TOOLKIT.$${QUERY_TOOLKIT_PROPERTY} )\\n )" )
