# -- Metadata generator conditions -- #

!TEMPLATE( aux|binary ): \
    qswarning( "'$${TEMPLATE}' target not supported. LDTools meta-project generation skipped..." )

else: !win32: \
    qswarning( "'$${TOOLKIT.host.platform}' platform not supported. LDTools meta-project generation skipped..." )
    
else: isEmpty( PACKAGE ): \
    qswarning( "Empty PACKAGE variable value detected. LDTools meta-project generation skipped..." )
        
else: isEmpty( INSTALLDIR ): \
    qswarning( "Empty INSTALLDIR variable value detected. LDTools meta-project generation skipped..." )
    
else {


    on_writer_start() {
    
        # -- Binary features resolution -- #

        # For any binary target, following features will be taken into account:
        #   - qt-based and boost-based flags
        #   - static, shared, static_and_shared and plugin flags for library target

        TEMPLATE( binary ): \
            _config = $$remove( CONFIG, ^(?!qt$|boost$).*$ )

        TEMPLATE( lib ) {
        
            _config *= $$remove( CONFIG, ^(?!static$|shared$|static_and_shared$|plugin$).*$ )

            contains( _config, static_and_shared ): \
                _config = $$remove( _config, ^(?:static|shared)$ )
        }

        _config = $$unique( _config )
    }
    
    build_pass() {
    
        # -- Library dependencies resolution -- #
        
        !isEmpty( LIBS ) {
        
            for( library, LIBS ): \
                !startsWith( library, -L ) {
                
                    startsWith( library, -l ): \
                        library = $$remove( library, ^-l )
                        
                    else { 
                    
                        library = $$basename( library )
                        library = $$remove( library, \\.\\w+(?:(\\.\\d+){1,3})?$ )
                    }
                    
                    _libraries *= $${library}
                }
        }

        !isEmpty( COMBINED_LIBS ) {
        
            for( library, COMBINED_LIBS ) {
            
                library = $$basename( library )
                library = $$remove( library, \\.\\w+$ )
                
                _libraries *= $${library}
            }
        }
        
        
        # -- Plugin dependencies resolution -- #

        for( plugin, PLUGINS ) {
        
            plugin = $$basename( plugin )
            plugin = $$remove( plugin, \\.\\w+$ )
            
            _plugins *= $${plugin}
        }
    }
    
    
    # -- LDTools meta-project file generation -- #

    # {
    #     "properties":
    #     {
    #         "TARGET":     "<target name>",
    #         "TEMPLATE":   "<target type>",
    #         "CONFIG":     "<target features>",                (optional)
    #
    #         "PACKAGE":    "<package path relative to project path>",
    #         "INSTALLDIR": "<installation path relative to project path>"
    #     },
    #  
    #     "dependencies[.config]":                              (optional)
    #     {
    #         "LIBRARIES": <array of linked library targets>,   (optional)
    #         "PLUGINS":   <array of linked plugin targets>     (optional)
    #     }
    # }

    # with [config] equals to:
    #   - (static|shared) if static_and_shared option is enabled

    on_writer_start() {
    
        append_line(         "$${LITERAL_OPEN_BRACE}" )
        append_line(         "    \"description\": \"LDTools meta-project file generated by qmake $$[QMAKE_VERSION] ($$[QT_VERSION]).\"," )
        append_line()
        append_line(         "    \"properties\":" )
        append_line(         "    {" )
        append_line(         "        \"TARGET\": \"$$TARGET()\"," )
        append_line(         "        \"TEMPLATE\": \"$$remove( TEMPLATE, ^vc )\"," )
            
        !isEmpty( _config ): \
            append_line(     "        \"CONFIG\": \"$${_config}\"," )
        
        append_line()
        append_line(         "        \"PACKAGE\": \"$$relative_path( $${PACKAGE}, $${_PRO_FILE_PWD_} )\"," )
        append_line(         "        \"INSTALLDIR\": \"$${INSTALLDIR}\"" )
        append_line(         "    }" )

        unset( _config )
    }
    
    build_pass( binary ) {

        static_and_shared {
        
            TEMPLATE( shared ):       _depend_config = .shared
            else: TEMPLATE( static ): _depend_config = .static
        }

        !isEmpty( _libraries )| \
        !isEmpty( _plugins ) {

            append_string( "," )
        
            append_line()
            append_line(     "    \"dependencies$${_depend_config}\":" )
            append_line(     "    {" )

            !isEmpty( _libraries ) {
            
                append_line( "        \"LIBRARIES\": [ $$join( _libraries, "$${LITERAL_QUOTES}, $${LITERAL_QUOTES}", $${LITERAL_QUOTES}, $${LITERAL_QUOTES} ) ]" )
                
                !isEmpty( _plugins ): \
                    append_string( "," )
            }
            
            !isEmpty( _plugins ): \
                append_line( "        \"PLUGINS\": [ $$join( _plugins, "$${LITERAL_QUOTES}, $${LITERAL_QUOTES}", $${LITERAL_QUOTES}, $${LITERAL_QUOTES} ) ]" )
            
            append_line(     "    }" )
        }
        
        unset( _libraries )
        unset( _plugins )

        unset( _depend_config )
    }
    
    on_writer_end(): \
        append_line(         "$${LITERAL_CLOSE_BRACE}" )
}
