macro(cstoolkit_fetch_codx fetch_codx_name)
    set(fetch_codx_OPTIONS SNAPSHOT)
    set(fetch_codx_UNIQUE EDITION VERSION EXPORT_CONTROL)
    set(fetch_codx_MULTIPLE)
    cmake_parse_arguments(_fetch_codx "${fetch_codx_OPTIONS}" "${fetch_codx_UNIQUE}" "${fetch_codx_MULTIPLE}" ${ARGN})

    if("${fetch_codx_name}" STREQUAL "LOC" OR "${fetch_codx_name}" STREQUAL "DlpxHiCodx")
        set(fetch_codx_link "LOC")
        set(fetch_codx_package_name "DlpxHiCodx")
    elseif("${fetch_codx_name}" MATCHES "Codx(.+)")
        set(fetch_codx_link "${CMAKE_MATCH_1}")
        set(fetch_codx_package_name "${fetch_codx_name}")
    else()
        set(fetch_codx_link "${fetch_codx_name}")
        set(fetch_codx_package_name "Codx${fetch_codx_link}")
    endif()

    if(fetch_codx_link STREQUAL "LOC")
        if(_fetch_codx_SNAPSHOT)
            set(fetch_codx_root "snapshot/Frameworks/DLPX-HI/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/master")
        else()
            set(fetch_codx_root "release/Frameworks/DLPX-HI/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/${_fetch_codx_VERSION}")
        endif()
        set(fetch_codx_file "${fetch_codx_link}${_fetch_codx_EDITION}_${_fetch_codx_VERSION}_${_fetch_codx_EXPORT_CONTROL}_${CSTOOLKIT_BUILD_MKSPECS}.7z")
    else()
        if(_fetch_codx_SNAPSHOT)
            set(fetch_codx_root "snapshot/Protocols/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/${_fetch_codx_VERSION}/internal")
        else()
            set(fetch_codx_root "release/Protocols/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/${_fetch_codx_VERSION}/internal")
        endif()
        set(fetch_codx_file "${fetch_codx_link}${_fetch_codx_EDITION}-internal_${_fetch_codx_VERSION}_${_fetch_codx_EXPORT_CONTROL}_${CSTOOLKIT_BUILD_MKSPECS}.zip")
    endif()

    cstoolkit_fetch_package(${fetch_codx_package_name} "${CSTOOLKIT_ARTIFACTORY_URL}/${fetch_codx_root}/${fetch_codx_file}" CODX ${ARGN})

    unset(fetch_codx_OPTIONS)
    unset(fetch_codx_UNIQUE)
    unset(fetch_codx_MULTIPLE)
    unset(fetch_codx_link)
    unset(fetch_codx_name)
    unset(_fetch_codx_EDITION)
    unset(_fetch_codx_VERSION)
    unset(_fetch_codx_EXPORT_CONTROL)
    unset(fetch_codx_root)
    unset(fetch_codx_file)
endmacro()
