macro(cstoolkit_fetch_codx fetch_codx_name)
    set(fetch_codx_OPTIONS SNAPSHOT)
    set(fetch_codx_UNIQUE EDITION VERSION EXPORT_CONTROL MKSPECS)
    set(fetch_codx_MULTIPLE)
    cmake_parse_arguments(_fetch_codx "${fetch_codx_OPTIONS}" "${fetch_codx_UNIQUE}" "${fetch_codx_MULTIPLE}" ${ARGN})

    if("${fetch_codx_name}" STREQUAL "LOC" OR "${fetch_codx_name}" STREQUAL "DlpxHiCodx")
        set(fetch_codx_link "LOC")
        set(fetch_codx_package_name "DlpxHiCodx")
    elseif("${fetch_codx_name}" MATCHES "Codx(.+)")
        set(fetch_codx_link "${CMAKE_MATCH_1}")
        set(fetch_codx_package_name "${fetch_codx_name}")
    else()
        set(fetch_codx_link "${fetch_codx_name}")
        set(fetch_codx_package_name "Codx${fetch_codx_link}")
    endif()

    if(NOT _fetch_codx_MKSPECS)
        # Use CSTOOLKIT_EXTERNAL_MKSPECS if set, otherwise use CSTOOLKIT_BUILD_MKSPECS
        if(CSTOOLKIT_EXTERNAL_MKSPECS)
            set(_fetch_codx_MKSPECS "${CSTOOLKIT_EXTERNAL_MKSPECS}")
        else()
            set(_fetch_codx_MKSPECS "${CSTOOLKIT_BUILD_MKSPECS}")
        endif()
    endif()

    if(_fetch_codx_EXPORT_CONTROL)
        set(_fetch_codx_EXPORT_CONTROL "_${_fetch_codx_EXPORT_CONTROL}")
    endif()

    if(_fetch_codx_SNAPSHOT)
        set(fetch_codx_root "snapshot")
    else()
        set(fetch_codx_root "release")
    endif()

    if(fetch_codx_link STREQUAL "LOC")
        if(_fetch_codx_SNAPSHOT AND NOT _fetch_codx_VERSION)
            set(fetch_codx_root "${fetch_codx_root}/Frameworks/DLPX-HI/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/master")
        else()
            set(fetch_codx_root "${fetch_codx_root}/Frameworks/DLPX-HI/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/${_fetch_codx_VERSION}")
        endif()
        set(fetch_codx_file "${fetch_codx_link}${_fetch_codx_EDITION}_${_fetch_codx_VERSION}${_fetch_codx_EXPORT_CONTROL}_${_fetch_codx_MKSPECS}.7z")
    else()
        set(fetch_codx_root "${fetch_codx_root}/Protocols/CODX/${fetch_codx_link}/${_fetch_codx_EDITION}/${_fetch_codx_VERSION}/internal")
        set(fetch_codx_file "${fetch_codx_link}${_fetch_codx_EDITION}-internal_${_fetch_codx_VERSION}${_fetch_codx_EXPORT_CONTROL}_${_fetch_codx_MKSPECS}.zip")
    endif()

    cstoolkit_fetch_package(${fetch_codx_package_name} "${CSTOOLKIT_ARTIFACTORY_URL}/${fetch_codx_root}/${fetch_codx_file}" CODX ${ARGN})

    unset(fetch_codx_OPTIONS)
    unset(fetch_codx_UNIQUE)
    unset(fetch_codx_MULTIPLE)
    unset(fetch_codx_link)
    unset(fetch_codx_name)
    unset(fetch_codx_package_name)
    unset(_fetch_codx_SNAPSHOT)
    unset(_fetch_codx_EDITION)
    unset(_fetch_codx_VERSION)
    unset(_fetch_codx_EXPORT_CONTROL)
    unset(_fetch_codx_MKSPECS)
    unset(fetch_codx_root)
    unset(fetch_codx_file)
endmacro()
