# Define ESC character
string(ASCII 27 COLOR_ESC)

# Reset
set(COLOR_RESET "${COLOR_ESC}[0m")

# Normal colors
set(COLOR_BLACK "${COLOR_ESC}[30m")
set(COLOR_RED "${COLOR_ESC}[31m")
set(COLOR_GREEN "${COLOR_ESC}[32m")
set(COLOR_YELLOW "${COLOR_ESC}[33m")
set(COLOR_BLUE "${COLOR_ESC}[34m")
set(COLOR_MAGENTA "${COLOR_ESC}[35m")
set(COLOR_CYAN "${COLOR_ESC}[36m")
set(COLOR_WHITE "${COLOR_ESC}[37m")
set(COLOR_GREY "${COLOR_ESC}[90m")

# Bold colors
set(COLOR_BLACK_BOLD "${COLOR_ESC}[1;30m")
set(COLOR_RED_BOLD "${COLOR_ESC}[1;31m")
set(COLOR_GREEN_BOLD "${COLOR_ESC}[1;32m")
set(COLOR_YELLOW_BOLD "${COLOR_ESC}[1;33m")
set(COLOR_BLUE_BOLD "${COLOR_ESC}[1;34m")
set(COLOR_MAGENTA_BOLD "${COLOR_ESC}[1;35m")
set(COLOR_CYAN_BOLD "${COLOR_ESC}[1;36m")
set(COLOR_WHITE_BOLD "${COLOR_ESC}[1;37m")
set(COLOR_GREY_BOLD "${COLOR_ESC}[1;90m")
