# FILE_LIST : List of the files to copy
# DESTINATION : Directory where files will be copy, if the directory doesn't exist it creates it

message(STATUS "========================= Script Copy.cmake =========================")
message("DESTINATION : ${DESTINATION}")
message("FILE_LIST : ${FILE_LIST}")
message("DIRECTORY_LIST : ${DIRECTORY_LIST}")

if (NOT EXISTS ${DESTINATION})
    message("Destination directory is not existing.\nCreating ${DESTINATION}")
    file(MAKE_DIRECTORY ${DESTINATION})
endif()

if (FILE_LIST)
    message(STATUS "========= Mode File =========")
    set(LIST_SEPARATED ${FILE_LIST})
    separate_arguments(LIST_SEPARATED)

    foreach(file ${LIST_SEPARATED})
        if (EXISTS ${file})
            message("Adding files : ${file} for copy")
            list(APPEND EXISTING_FILES ${file})       
        else()
            if(NO_ERROR)
                message("Unable to copy ${file}, the file doesn't exist")
            else()
                message(FATAL_ERROR "Unable to copy ${file}, the file doesn't exist")
            endif()
        endif()
    endforeach()

    message(STATUS "\nCopying files to ${DESTINATION}\n")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${EXISTING_FILES} ${DESTINATION})
endif()
if(DIRECTORY_LIST)
    message(STATUS "========= Mode Directory =========")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory_if_different ${DIRECTORY_LIST} ${DESTINATION})
endif()
if(NOT FILE_LIST AND NOT DIRECTORY_LIST)
    message(FATAL_ERROR "No directory or file specified for the copy")
endif()