macro(cfmake print_var)
    # Calls cfmake_print or cfmake_print_genex depending on value
    if(DEFINED ${print_var})
        string(FIND "${${print_var}}" "$<" _genex_pos)
        if(_genex_pos GREATER -1)
            cfmake_print_genex(${print_var})
        else()
            cfmake_print(${print_var})
        endif()
    else()
        string(FIND "${print_var}" "$<" _genex_pos)
        if(_genex_pos GREATER -1)
            cfmake_print_genex(${print_var})
        else()
            cfmake_print(${print_var})
        endif()
    endif()
endmacro()

function(cfmake_print print_var)
    if(DEFINED ${print_var})
        message(${COLOR_CYAN_BOLD} "${print_var}: '${${print_var}}'" ${COLOR_RESET})
    else()
        message(${COLOR_CYAN_BOLD} "${print_var}: UNDEFINED" ${COLOR_RESET})
    endif()
endfunction()

set_property(GLOBAL PROPERTY CFMAKE_DEBUG_PRINT_GENEX "")

function(cfmake_print_genex genex_var)
    get_property(CFMAKE_DEBUG_PRINT_GENEX_LIST GLOBAL PROPERTY CFMAKE_DEBUG_PRINT_GENEX)
    if(DEFINED "${genex_var}")
        string(REPLACE ";" "\;" escaped_str "${${genex_var}}")
        list(APPEND CFMAKE_DEBUG_PRINT_GENEX_LIST "${genex_var}: '${escaped_str}'")
    else()
        string(REPLACE ";" "\;" escaped_str "${genex_var}")
        list(APPEND CFMAKE_DEBUG_PRINT_GENEX_LIST "GENEX: '${escaped_str}'")
    endif()
    set_property(GLOBAL PROPERTY CFMAKE_DEBUG_PRINT_GENEX "${CFMAKE_DEBUG_PRINT_GENEX_LIST}")
endfunction()

function(cfmake_internal_print_genex_post_configure)
    get_property(CFMAKE_DEBUG_PRINT_GENEX_LIST GLOBAL PROPERTY CFMAKE_DEBUG_PRINT_GENEX)
    if(CFMAKE_DEBUG_PRINT_GENEX_LIST)
        foreach(CFMAKE_DEBUG_PRINT_GENEX IN LISTS CFMAKE_DEBUG_PRINT_GENEX_LIST)
            add_custom_command(TARGET CFMAKE POST_BUILD COMMAND "${CMAKE_COMMAND}" -E echo "\"${CFMAKE_DEBUG_PRINT_GENEX}\"" VERBATIM)
        endforeach()
    endif()
endfunction()
