function(cstoolkit_print print_var)
    if(DEFINED ${print_var})
        message(${COLOR_CYAN_BOLD} "${print_var}: '${${print_var}}'" ${COLOR_RESET})
    else()
        message(${COLOR_CYAN_BOLD} "${print_var}: UNDEFINED" ${COLOR_RESET})
    endif()
endfunction()

set_property(GLOBAL PROPERTY CSTOOLKIT_DEBUG_PRINT_GENEX "")

function(cstoolkit_print_genex genex_var)
    get_property(CSTOOLKIT_DEBUG_PRINT_GENEX_LIST GLOBAL PROPERTY CSTOOLKIT_DEBUG_PRINT_GENEX)
    if(DEFINED "${genex_var}")
        string(REPLACE ";" "\;" escaped_str "${${genex_var}}")
        list(APPEND CSTOOLKIT_DEBUG_PRINT_GENEX_LIST "${genex_var}: '${escaped_str}'")
    else()
        string(REPLACE ";" "\;" escaped_str "${genex_var}")
        list(APPEND CSTOOLKIT_DEBUG_PRINT_GENEX_LIST "GENEX: '${escaped_str}'")
    endif()
    set_property(GLOBAL PROPERTY CSTOOLKIT_DEBUG_PRINT_GENEX "${CSTOOLKIT_DEBUG_PRINT_GENEX_LIST}")
endfunction()

function(cstoolkit_internal_print_genex_post_configure)
    get_property(CSTOOLKIT_DEBUG_PRINT_GENEX_LIST GLOBAL PROPERTY CSTOOLKIT_DEBUG_PRINT_GENEX)
    if(CSTOOLKIT_DEBUG_PRINT_GENEX_LIST)
        foreach(CSTOOLKIT_DEBUG_PRINT_GENEX IN LISTS CSTOOLKIT_DEBUG_PRINT_GENEX_LIST)
            add_custom_command(TARGET CSTOOLKIT COMMAND "${CMAKE_COMMAND}" -E echo "\"${CSTOOLKIT_DEBUG_PRINT_GENEX}\"" VERBATIM)
        endforeach()
    endif()
endfunction()
