include(FetchContent)

macro(cstoolkit_fetch_artifactory FETCH_NAME)
    set(FETCH_OPTIONS QT LEGACY)
    set(FETCH_UNIQUE URL VERSION FOLDER ALIAS)
    set(FETCH_MULTIPLE)
    cmake_parse_arguments(FETCH "${FETCH_OPTIONS}" "${FETCH_UNIQUE}" "${FETCH_MULTIPLE}" ${ARGN})

    if(FETCH_ALIAS)
        set(FETCH_PACKAGE_NAME ${FETCH_ALIAS})
    else()
        set(FETCH_PACKAGE_NAME ${FETCH_NAME})
    endif()
    string(TOUPPER "${FETCH_PACKAGE_NAME}" FETCH_PACKAGE_NAME_UPPER)

    string(TIMESTAMP CSTOOLKIT_FETCH_START_TIME "%s%f")
    message(STATUS "CSToolkit: Fetch ${FETCH_PACKAGE_NAME}")

    if(NOT FETCH_URL AND NOT FETCH_VERSION)
        message(SEND_ERROR "CSToolkit: cstoolkit_fetch_artifactory: VERSION or URL parameter must be defined.")
        return()
    else()
        if(NOT FETCH_URL)
            if(NOT FETCH_FOLDER)
                set(FETCH_FOLDER "thirdParty")
            endif()
            set(FETCH_URL "${CSTOOLKIT_ARTIFACTORY_URL}/${FETCH_FOLDER}/${FETCH_NAME}/${FETCH_VERSION}/${FETCH_NAME}_${FETCH_VERSION}")
            if(FETCH_QT)
                if(NOT QT_VERSION)
                    message(SEND_ERROR "CSToolkit: cstoolkit_fetch_artifactory: Qt was not found, unable to use option 'QT'")
                    return()
                endif()
                if(FETCH_LEGACY)
                    set(FETCH_URL "${FETCH_URL}_${CSTOOLKIT_BUILD_MKSPECS}-QT${QT_VERSION}")
                else()
                    set(FETCH_URL "${FETCH_URL}_${CSTOOLKIT_BUILD_MKSPECS_QT}")
                endif()
            else()
                set(FETCH_URL "${FETCH_URL}_${CSTOOLKIT_BUILD_MKSPECS}")
            endif()
            if(FETCH_LEGACY)
                set(FETCH_URL "${FETCH_URL}.zip")
            else()
                set(FETCH_URL "${FETCH_URL}.7z")
            endif()
        endif()

        FetchContent_Declare(${FETCH_PACKAGE_NAME}
            URL "${FETCH_URL}"
            SOURCE_DIR "${CSTOOLKIT_EXTERNALS}/${FETCH_PACKAGE_NAME}"
        )

        
        if("${FETCH_URL}" STREQUAL "${CSTOOLKIT_FECTH_ARTIFACTORY_POPULATED_${FETCH_PACKAGE_NAME_UPPER}}")
            set(FETCH_POPULATED TRUE)
        else()
            set(CSTOOLKIT_FECTH_ARTIFACTORY_POPULATED_${FETCH_PACKAGE_NAME_UPPER} "${FETCH_URL}" CACHE INTERNAL "${FETCH_PACKAGE_NAME} populated url.")
            set(FETCH_POPULATED FALSE)
            #message(STATUS "CSToolkit: Fetch ${FETCH_PACKAGE_NAME}")
        endif()

        FetchContent_MakeAvailable(${FETCH_PACKAGE_NAME})

        if(NOT FETCH_POPULATED)
            #message(STATUS "CSToolkit: Fetch ${FETCH_PACKAGE_NAME} - done")
        endif()

        if(FETCH_LEGACY)
            if(EXISTS "${CSTOOLKIT_EXTERNALS}/${FETCH_PACKAGE_NAME}/${FETCH_PACKAGE_NAME}Config.cmake" AND NOT CSTOOLKIT_FECTH_ARTIFACTORY_LEGACY_${FETCH_PACKAGE_NAME_UPPER})
                message(STATUS "CSToolkit: Overwriting ${FETCH_PACKAGE_NAME}Config.cmake with generated legacy suport Config file.")
            endif()
            set(CSTOOLKIT_FECTH_ARTIFACTORY_LEGACY_${FETCH_PACKAGE_NAME_UPPER} TRUE CACHE INTERNAL "Legacy mode used for ${FETCH_PACKAGE_NAME}")
            configure_file(${CSTOOLKIT_ROOT_DIR}/templates/FetchLegacyConfig.${CSTOOLKIT_HOST_PLATFORM}.in "${CSTOOLKIT_EXTERNALS}/${FETCH_PACKAGE_NAME}/${FETCH_PACKAGE_NAME}Config.cmake" @ONLY)
        else()
            set(CSTOOLKIT_FECTH_ARTIFACTORY_LEGACY_${FETCH_PACKAGE_NAME_UPPER} FALSE CACHE INTERNAL "Legacy mode used for ${FETCH_PACKAGE_NAME}")
        endif()

        set(${FETCH_PACKAGE_NAME_UPPER}_ROOT "${CSTOOLKIT_EXTERNALS}/${FETCH_PACKAGE_NAME}" CACHE INTERNAL "Defined by call to cstoolkit_fetch_artifactory")
        set(FETCH_PACKAGE_HINTS "${${FETCH_PACKAGE_NAME_UPPER}_ROOT}")

        find_package(${FETCH_PACKAGE_NAME} QUIET MODULE GLOBAL)
        if(NOT ${${FETCH_PACKAGE_NAME}_FOUND})
            if(FETCH_ALIAS) # If ALIAS is Provided find_package is REQUIRED and no try with lowercase
                find_package(${FETCH_PACKAGE_NAME} REQUIRED CONFIG GLOBAL NO_DEFAULT_PATH HINTS "${FETCH_PACKAGE_HINTS}")
            else()
                find_package(${FETCH_PACKAGE_NAME} QUIET CONFIG GLOBAL NO_DEFAULT_PATH HINTS "${FETCH_PACKAGE_HINTS}")
                if(NOT ${${FETCH_PACKAGE_NAME}_FOUND})
                    string(TOLOWER ${FETCH_PACKAGE_NAME} FETCH_PACKAGE_NAME_LOWER)
                    if(NOTFETCH_PACKAGE_NAME STREQUAL FETCH_PACKAGE_NAME_LOWER)
                        find_package(${FETCH_PACKAGE_NAME_LOWER} QUIET MODULE GLOBAL)
                        if(NOT ${${FETCH_PACKAGE_NAME}_FOUND})
                            find_package(${FETCH_PACKAGE_NAME_LOWER} QUIET CONFIG GLOBAL NO_DEFAULT_PATH HINTS "${FETCH_PACKAGE_HINTS}")
                        endif()
                    endif()
                endif()
            endif()
        endif()
    endif()

    string(TIMESTAMP CSTOOLKIT_FETCH_END_TIME "%s%f")
    math(EXPR CSTOOLKIT_FETCH_elapsed "${CSTOOLKIT_FETCH_END_TIME}-${CSTOOLKIT_FETCH_START_TIME}")
    math(EXPR CSTOOLKIT_FETCH_second_elapsed "${CSTOOLKIT_FETCH_elapsed}/1000000")
    math(EXPR CSTOOLKIT_FETCH_tenth_elapsed "(${CSTOOLKIT_FETCH_elapsed}-${CSTOOLKIT_FETCH_second_elapsed}*1000000+50000)/100000")
    message(STATUS "CSToolkit: Fetch ${FETCH_PACKAGE_NAME} - done (${CSTOOLKIT_FETCH_second_elapsed}.${CSTOOLKIT_FETCH_tenth_elapsed}s)")

    # unset because this is a macro
    unset(CSTOOLKIT_FETCH_START_TIME)
    unset(CSTOOLKIT_FETCH_END_TIME)
    unset(CSTOOLKIT_FETCH_elapsed)
    unset(CSTOOLKIT_FETCH_second_elapsed)
    unset(CSTOOLKIT_FETCH_tenth_elapsed)
    unset(FETCH_ALIAS)
    unset(FETCH_PACKAGE_NAME)
    unset(FETCH_URL)
    unset(FETCH_VERSION)
    unset(FETCH_FOLDER)
    unset(FETCH_QT)
    unset(FETCH_LEGACY)
    unset(FETCH_POPULATED)
    unset(FETCH_PACKAGE_NAME_UPPER)
    unset(FETCH_PACKAGE_NAME_LOWER)
    unset(FETCH_PACKAGE_HINTS)
endmacro()

function(cstoolkit_download_url URL OUTPUT_VAR)
    set(options NO_EXTRACT)
    set(one_value_args)
    set(multi_value_args)
    cmake_parse_arguments(PARSE_ARGV 2 DOWNLOAD "${options}" "${one_value_args}" "${multi_value_args}")

    cmake_path(GET URL STEM LAST_ONLY _FILENAME)
    string(MD5 _HASH ${URL})
    string(SUBSTRING ${_HASH} 0 8 _HASH)
    FetchContent_Declare(cstoolkit_dl_${_HASH}
        URL "${URL}"
        SOURCE_DIR "${CSTOOLKIT_EXTERNALS}/${_FILENAME}_${_HASH}"
        DOWNLOAD_NO_EXTRACT ${DOWNLOAD_NO_EXTRACT}
    )

    FetchContent_MakeAvailable(cstoolkit_dl_${_HASH})

    if(DOWNLOAD_NO_EXTRACT)
        cmake_path(GET URL FILENAME _FULLFILENAME)
        set(${OUTPUT_VAR} "${CSTOOLKIT_EXTERNALS}/${_FILENAME}_${_HASH}/${_FULLFILENAME}")
    else()
        set(${OUTPUT_VAR} "${CSTOOLKIT_EXTERNALS}/${_FILENAME}_${_HASH}")
    endif()

    set(${OUTPUT_VAR} ${${OUTPUT_VAR}} PARENT_SCOPE)
endfunction()
