function(cstoolkit_file_realpath_list filelist)
    set(_templist "${${filelist}}")
    set(${filelist} "")
    foreach(_file ${_templist})
        cmake_path(ABSOLUTE_PATH _file NORMALIZE)
        list(APPEND ${filelist} "${_file}")
    endforeach()
    set(${filelist} "${${filelist}}" PARENT_SCOPE)
endfunction()

function(cstoolkit_file_glob_recurse_dirs output glob dirs)
    set(${output} "")
    foreach(_dir ${dirs})
        foreach(_g ${glob})
            set(_tempfiles "")
            file(GLOB_RECURSE _tempfiles "${_dir}/${_g}")
            list(APPEND ${output} "${_tempfiles}")
        endforeach()
    endforeach()
    set(${output} "${${output}}" PARENT_SCOPE)
endfunction()

function(cstoolkit_relative_path_dirs file)
    set(PARAM_OPTIONS "")
    set(PARAM_UNIQUE OUTPUT_VARIABLE)
    set(PARAM_MULTIPLE BASE_DIRECTORIES)

    cmake_parse_arguments(PARSE_ARGV 1 PARAM "${PARAM_OPTIONS}" "${PARAM_UNIQUE}" "${PARAM_MULTIPLE}")

    set(${output} "")
    foreach(_dir ${PARAM_BASE_DIRECTORIES})
        cmake_path(RELATIVE_PATH ${file} BASE_DIRECTORY ${_dir} OUTPUT_VARIABLE ${PARAM_OUTPUT_VARIABLE})
        cmake_path(IS_RELATIVE ${PARAM_OUTPUT_VARIABLE} is_base_dir)
        if(is_base_dir)
            set(${PARAM_OUTPUT_VARIABLE} "${${PARAM_OUTPUT_VARIABLE}}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${PARAM_OUTPUT_VARIABLE} "${${PARAM_OUTPUT_VARIABLE}}" PARENT_SCOPE)
endfunction()

function(cstoolkit_source_group)
    set(PARAM_OPTIONS "")
    set(PARAM_UNIQUE PREFIX)
    set(PARAM_MULTIPLE TREE FILES)

    cmake_parse_arguments(PARSE_ARGV 0 PARAM "${PARAM_OPTIONS}" "${PARAM_UNIQUE}" "${PARAM_MULTIPLE}")

    foreach(_tree ${PARAM_TREE})
        set(_files "${PARAM_FILES}")
        list(FILTER _files INCLUDE REGEX "^${_tree}/")
        if(_files)
            source_group(TREE ${_tree} PREFIX "${PARAM_PREFIX}" FILES ${_files})
            list(REMOVE_ITEM PARAM_FILES ${_files})
        endif()
    endforeach()

    if(PARAM_FILES)
        source_group("${PARAM_PREFIX}" FILES ${PARAM_FILES})
    endif()
endfunction()
