function(cstoolkit_genex_list_intersection lista listb outputlist)
    set(aminusb "$<LIST:REMOVE_ITEM,${lista},${listb}>")
    
    set(bminusa "$<LIST:REMOVE_ITEM,${listb},${lista}>")

    set(${outputlist} "${lista};${listb}")
    set(${outputlist} "$<LIST:REMOVE_DUPLICATES,${${outputlist}}>")
    set(${outputlist} "$<LIST:REMOVE_ITEM,${${outputlist}},${aminusb};${bminusa}>")
    set(${outputlist} "$<JOIN:${${outputlist}},;>") # remove empty elements

    set(${outputlist} "${${outputlist}}" PARENT_SCOPE)
endfunction()

function(cstoolkit_genex_extract input outputvar genexprefix)
    #message("Entry:   ${input}")
    string(REGEX MATCH "\\$<.*>" genex "${input}")
    if(NOT genex)
        #message("Not genex: '${input}'")
        set(${outputvar} "${input}" PARENT_SCOPE)
        set(${genexprefix} "" PARENT_SCOPE)
        return()
    endif()

    set(${genexprefix} "")
    set(genex_cnt 0)
    set(output "")
    set(nesting_level 0)
    foreach(elem ${input})
        #message("Elem! ${elem}")
        #message("nesting_level! ${nesting_level}")
        if(nesting_level EQUAL 0)
            string(FIND "${elem}" "$<" genexStartPos)
            if(genexStartPos EQUAL -1)
                #message("not genex: ${elem}")
                list(APPEND output "${elem}")
                continue()
            endif()
            #start of a genex
            math(EXPR nesting_level "${nesting_level}+1")
            math(EXPR genex_cnt "${genex_cnt}+1")
            set(${genexprefix}${genex_cnt} "${elem}")
            list(APPEND ${genexprefix} "${genexprefix}${genex_cnt}")
            #searching genex end
            math(EXPR genexStartPos "${genexStartPos}+2")
            string(SUBSTRING "${elem}" ${genexStartPos} -1 subelem)
            #message("Substring: '${subelem}'")
            string(FIND "${subelem}" "$<" genexStartPos)
            string(FIND "${subelem}" ">" genexEndPos)
            while(NOT genexStartPos EQUAL genexEndPos)
                if(genexStartPos LESS genexEndPos AND NOT genexStartPos EQUAL -1)
                    math(EXPR nesting_level "${nesting_level}+1")
                    math(EXPR genexStartPos "${genexStartPos}+2")
                    string(SUBSTRING "${subelem}" ${genexStartPos} -1 subelem)
                else()
                    math(EXPR nesting_level "${nesting_level}-1")
                    math(EXPR genexEndPos "${genexEndPos}+1")
                    string(SUBSTRING "${subelem}" ${genexEndPos} -1 subelem)
                endif()
                string(FIND "${subelem}" "$<" genexStartPos)
                string(FIND "${subelem}" ">" genexEndPos)
            endwhile()
        else()
            set(${genexprefix}${genex_cnt} "${${genexprefix}${genex_cnt}};${elem}")
            set(subelem "${elem}")
            string(FIND "${subelem}" "$<" genexStartPos)
            string(FIND "${subelem}" ">" genexEndPos)
            while(NOT genexStartPos EQUAL genexEndPos)
                if(genexStartPos LESS genexEndPos AND NOT genexStartPos EQUAL -1)
                    math(EXPR nesting_level "${nesting_level}+1")
                    math(EXPR genexStartPos "${genexStartPos}+2")
                    string(SUBSTRING "${subelem}" ${genexStartPos} -1 subelem)
                else()
                    math(EXPR nesting_level "${nesting_level}-1")
                    math(EXPR genexEndPos "${genexEndPos}+1")
                    string(SUBSTRING "${subelem}" ${genexEndPos} -1 subelem)
                endif()
                string(FIND "${subelem}" "$<" genexStartPos)
                string(FIND "${subelem}" ">" genexEndPos)
            endwhile()
        endif()
    endforeach()

    set(${outputvar} "${output}" PARENT_SCOPE)
    set(${genexprefix} "${${genexprefix}}" PARENT_SCOPE)
    foreach(elem ${${genexprefix}})
        #message("genex: ${${elem}}")
        set(${elem} "${${elem}}" PARENT_SCOPE)
    endforeach()
    
endfunction()

function(cstoolkit_genex_cleanup input outputvar)
    message("Entry:   ${input}")
    string(REGEX MATCH "\\$<.*>" genex "${input}")
    if(NOT genex)
        message("Not genex: '${input}'")
        set(${outputvar} "${input}" PARENT_SCOPE)
        return()
    endif()

    set(index 0)
    set(literal_start 0)
    set(token_cnt 0)
    set(previous_dollar false)
    set(in_value false)
    string(LENGTH "${input}" input_length)
    set(output "")

    while(index LESS input_length)
        string(SUBSTRING "${input}" ${index} 1 char)
        if(char STREQUAL "$")
            set(previous_dollar true)
        else()
            if(char STREQUAL "<")
                if(token_cnt EQUAL 0)
                    set(params_cnt 0)
                    math(EXPR token_start ${index}+1)
                endif()
                math(EXPR token_cnt "${token_cnt}+1")
            elseif(char STREQUAL ">")
                math(EXPR token_cnt "${token_cnt}-1")
                if(token_cnt EQUAL 0)
                    if(NOT in_value)
                        math(EXPR token_end ${index}-1)
                    endif()

                    #########################################################
                    #START CLEANUP

                    math(EXPR literal_length "${token_start}-${literal_start}")
                    string(SUBSTRING "${input}" ${literal_start} ${literal_length} literal)
                    #message("Starlit: ${literal}")
                    set(output "${output}${literal}")

                    math(EXPR token_length "${token_end}-${token_start}+1")
                    string(SUBSTRING "${input}" ${token_start} ${token_length} token)
                    message("Token:   ${token}")
                    cstoolkit_genex_cleanup("${token}" token)
                    set(output "${output}${token}")
                
                    set(params_index 0)
                    while(params_index LESS params_cnt)
                        if(params_index EQUAL 0)
                            set(output "${output}:")
                        else()
                            set(output "${output},")
                        endif()
                        math(EXPR next_params_index "${params_index}+1")
                        math(EXPR token_value_length "${param${next_params_index}_index}-${param${params_index}_index}-1")
                        string(SUBSTRING "${input}" ${param${params_index}_index} ${token_value_length} token_value)
                        message("Param${params_index}: ${token_value}")
                        cstoolkit_genex_cleanup("${token_value}" token_value)
                        set(output "${output}${token_value}")
                        set(params_index ${next_params_index})
                    endwhile()

                    #END CLEANUP
                    #########################################################

                    set(literal_start ${index})
                endif()
            elseif(char STREQUAL ":" AND token_cnt EQUAL 1 AND NOT in_value)
                set(in_value true)
                math(EXPR token_end ${index}-1)
                math(EXPR param${params_cnt}_index ${index}+1)
                math(EXPR params_cnt "${params_cnt}+1")
                math(EXPR param${params_cnt}_index ${input_length})
            elseif(char STREQUAL "," AND token_cnt EQUAL 1)
                math(EXPR param${params_cnt}_index ${index}+1)
                math(EXPR params_cnt "${params_cnt}+1")
                math(EXPR param${params_cnt}_index ${input_length})
            endif()
            set(previous_dollar false)
        endif()
        math(EXPR index "${index}+1")
    endwhile()

    math(EXPR literal_length "${index}-${literal_start}")
    string(SUBSTRING "${input}" ${literal_start} ${literal_length} literal)
    message("End literal = ${literal}")
    set(output "${output}${literal}")

    message("Cleaned: ${output}")
    set(${outputvar} "${output}" PARENT_SCOPE)
endfunction()

function(cstoolkit_target_genex_eval target_name genex_var)
    set(target_genex_value "${${genex_var}}")
    string(REGEX MATCHALL "\\$<TARGET_PROPERTY:[^>]*>" _genex_target_properties "${${genex_var}}")
    foreach(_genex_target_property ${_genex_target_properties})
        if(_genex_target_property MATCHES "\\$<TARGET_PROPERTY:([^,>]+)>" )
            string(REPLACE "${_genex_target_property}" "$<TARGET_PROPERTY:${target_name},${CMAKE_MATCH_1}>" target_genex_value "${target_genex_value}")
        endif()
    endforeach()
    cstoolkit_genex_eval(target_genex_value)
    set(${genex_var} "${target_genex_value}" PARENT_SCOPE)
endfunction()

function(cstoolkit_genex_eval genex_var)
    cmake_parse_arguments(PARSE_ARGV 1 GENEX "RELAXED" "" "")
    set(genex_value)
    foreach(_genex_elem ${${genex_var}})
        string(REGEX MATCHALL "\\$<TARGET_PROPERTY:[^>]*>" _genex_elem_target_properties "${_genex_elem}")
        foreach(_genex_elem_target_property ${_genex_elem_target_properties})
            if(_genex_elem_target_property MATCHES "\\$<TARGET_PROPERTY:([^,]+),([^,>]+)>" )
                if(TARGET "${CMAKE_MATCH_1}")
                    get_target_property(_genex_elem_target_property_value "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
                    if(_genex_elem_target_property_value)
                        string(REPLACE "${_genex_elem_target_property}" "${_genex_elem_target_property_value}" _genex_elem "${_genex_elem}")
                    else()
                        string(REPLACE "${_genex_elem_target_property}" "" _genex_elem "${_genex_elem}")
                    endif()
                elseif(NOT GENEX_RELAXED)
                    message(FATAL_ERROR "Error evaluating generator expression:\n ${${genex_var}}\nTarget \"${CMAKE_MATCH_1}\" not found.")
                endif()
            elseif(NOT GENEX_RELAXED)
                message(FATAL_ERROR "Error evaluating generator expression:\n ${${genex_var}}\n$<TARGET_PROPERTY:...> expression requires one or two parameters")
            endif()
        endforeach()
        if(CMAKE_CONFIGURATION_TYPES)
            foreach(_config ${CMAKE_CONFIGURATION_TYPES})
                set(_genex_elem_value "${_genex_elem}")
                string(TOLOWER "${_config}" _config_lower)
                string(TOUPPER "${_config}" _config_upper)
                string(REPLACE "$<LOWER_CASE:$<CONFIG>>" "${_config_lower}" _genex_elem_value "${_genex_elem_value}")
                string(REPLACE "$<UPPER_CASE:$<CONFIG>>" "${_config_upper}" _genex_elem_value "${_genex_elem_value}")
                string(REPLACE "$<CONFIG>"               "${_config}"       _genex_elem_value "${_genex_elem_value}")
                list(APPEND genex_value "${_genex_elem_value}")
            endforeach()
        else()
            set(_config "${CMAKE_BUILD_TYPE}")
            set(_genex_elem_value "${_genex_elem}")
            string(TOLOWER "${CMAKE_BUILD_TYPE}" _config_lower)
            string(TOUPPER "${CMAKE_BUILD_TYPE}" _config_upper)
            string(REPLACE "$<LOWER_CASE:$<CONFIG>>" "${_config_lower}" _genex_elem_value "${_genex_elem_value}")
            string(REPLACE "$<UPPER_CASE:$<CONFIG>>" "${_config_upper}" _genex_elem_value "${_genex_elem_value}")
            string(REPLACE "$<CONFIG>"               "${_config}"       _genex_elem_value "${_genex_elem_value}")
            list(APPEND genex_value "${_genex_elem_value}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES genex_value)
    if(NOT GENEX_RELAXED AND genex_value MATCHES "\\$<.*>")
        message(FATAL_ERROR "Error evaluating generator expression:\n ${${genex_var}}\nExpression did not evaluate to a known generator expression")
    endif()
    set(${genex_var} "${genex_value}" PARENT_SCOPE)
endfunction()

function(cstoolkit_set_genex_source_file_properties genex_file)
    cstoolkit_genex_eval(genex_file)
    foreach(_file ${genex_file})
        set_source_files_properties("${_file}" ${ARGN})
    endforeach()
endfunction()
