# This is called after the call to project()
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  cmake_path(SET _install_path NORMALIZE "${CMAKE_BINARY_DIR}/../install")
  set(CMAKE_INSTALL_PREFIX "${_install_path}" CACHE PATH "Default install directory used by install()." FORCE)
endif()

include(${CMAKE_CURRENT_LIST_DIR}/Version.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/CppRules.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/mkspecs.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Qt.cmake)