# This is called after the call to project()
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/install" CACHE PATH "Project installation path" FORCE)
endif()

include(${CMAKE_CURRENT_LIST_DIR}/Version.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/CppRules.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/mkspecs.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Qt.cmake)