find_package(Git QUIET)

if(GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} describe --always --abbrev=8
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    OUTPUT_VARIABLE CSTOOLKIT_GIT_COMMIT)
    execute_process(COMMAND ${GIT_EXECUTABLE} status --short
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    OUTPUT_VARIABLE CSTOOLKIT_GIT_STATUS)
    if (NOT "${CSTOOLKIT_GIT_STATUS}" STREQUAL "")
        set(CSTOOLKIT_GIT_COMMIT "")
    endif()

    execute_process(COMMAND ${GIT_EXECUTABLE} describe --exact-match --tags
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    OUTPUT_VARIABLE CSTOOLKIT_GIT_TAG
                    ERROR_QUIET)

    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    OUTPUT_VARIABLE CSTOOLKIT_GIT_BRANCH)

    execute_process(COMMAND ${GIT_EXECUTABLE} log -n 1 --pretty=%cd --pretty=%cI
                    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                    OUTPUT_VARIABLE CSTOOLKIT_GIT_DATE)

    string(STRIP "${CSTOOLKIT_GIT_COMMIT}" CSTOOLKIT_GIT_COMMIT)
    string(STRIP "${CSTOOLKIT_GIT_TAG}" CSTOOLKIT_GIT_TAG)
    string(STRIP "${CSTOOLKIT_GIT_BRANCH}" CSTOOLKIT_GIT_BRANCH)
    string(STRIP "${CSTOOLKIT_GIT_DATE}" CSTOOLKIT_GIT_DATE)
endif()

# Get the version from the git
if (CSTOOLKIT_USE_GIT_TAG_VERSION)
    if(CSTOOLKIT_GIT_TAG MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        set(CSTOOLKIT_PROJECT_VERSION "${CSTOOLKIT_GIT_TAG}")
        message(STATUS "Project version from git tag: ${CSTOOLKIT_GIT_TAG}")
    elseif(CSTOOLKIT_GIT_BRANCH MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        set(CSTOOLKIT_PROJECT_VERSION "${CSTOOLKIT_GIT_BRANCH}")
        message(STATUS "Project version set from branch: ${CSTOOLKIT_GIT_BRANCH}")
    endif()
endif()

if(NOT CMAKE_PROJECT_VERSION OR
        NOT CSTOOLKIT_PROJECT_VERSION STREQUAL "0.0.0.0")

    if(NOT CSTOOLKIT_PROJECT_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        message(FATAL_ERROR "CSTOOLKIT_PROJECT_VERSION \"${CSTOOLKIT_PROJECT_VERSION}\" format invalid.")
    endif()

    string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?" _CSTOOLKIT_NORMALIZED_PROJECT_VERSION "${CSTOOLKIT_PROJECT_VERSION}")
    string(REGEX MATCH "-(.+)$" _CSTOOLKIT_PROJECT_VERSION_IDENTIFIER "${CSTOOLKIT_PROJECT_VERSION}")
    string(REGEX REPLACE "^-" "" _CSTOOLKIT_PROJECT_VERSION_IDENTIFIER "${_CSTOOLKIT_PROJECT_VERSION_IDENTIFIER}")

    string(REPLACE "." ";" _CSTOOLKIT_PROJECT_VERSION_LIST ${_CSTOOLKIT_NORMALIZED_PROJECT_VERSION})
    list(LENGTH _CSTOOLKIT_PROJECT_VERSION_LIST _CSTOOLKIT_PROJECT_VERSION_LENGTH)
    list(GET _CSTOOLKIT_PROJECT_VERSION_LIST 0 _CSTOOLKIT_PROJECT_VERSION_MAJOR)
    list(GET _CSTOOLKIT_PROJECT_VERSION_LIST 1 _CSTOOLKIT_PROJECT_VERSION_MINOR)
    list(GET _CSTOOLKIT_PROJECT_VERSION_LIST 2 _CSTOOLKIT_PROJECT_VERSION_PATCH)
    if(_CSTOOLKIT_PROJECT_VERSION_LENGTH GREATER 3)
        list(GET _CSTOOLKIT_PROJECT_VERSION_LIST 3 _CSTOOLKIT_PROJECT_VERSION_TWEAK)
    endif()

    set(CMAKE_PROJECT_VERSION ${_CSTOOLKIT_NORMALIZED_PROJECT_VERSION} CACHE INTERNAL "Value Computed by CSToolkit")
    # Because it is a static cache variable we have to set it as a internal cache then set it again as a local varaible
    set(CMAKE_PROJECT_VERSION ${_CSTOOLKIT_NORMALIZED_PROJECT_VERSION})
    
    set(CMAKE_PROJECT_VERSION_MAJOR ${_CSTOOLKIT_PROJECT_VERSION_MAJOR} CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_MINOR ${_CSTOOLKIT_PROJECT_VERSION_MINOR} CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_PATCH ${_CSTOOLKIT_PROJECT_VERSION_PATCH} CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_TWEAK ${_CSTOOLKIT_PROJECT_VERSION_TWEAK} CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_IDENTIFIER ${_CSTOOLKIT_PROJECT_VERSION_IDENTIFIER} CACHE INTERNAL "Value Computed by CSToolkit")
    # Because it is a static cache variable we have to set it as a internal cache then set it again as a local varaible
    set(CMAKE_PROJECT_VERSION_MAJOR ${_CSTOOLKIT_PROJECT_VERSION_MAJOR})
    set(CMAKE_PROJECT_VERSION_MINOR ${_CSTOOLKIT_PROJECT_VERSION_MINOR})
    set(CMAKE_PROJECT_VERSION_PATCH ${_CSTOOLKIT_PROJECT_VERSION_PATCH})
    set(CMAKE_PROJECT_VERSION_TWEAK ${_CSTOOLKIT_PROJECT_VERSION_TWEAK})
    set(CMAKE_PROJECT_VERSION_IDENTIFIER ${_CSTOOLKIT_PROJECT_VERSION_IDENTIFIER})
    
    set(PROJECT_VERSION ${_CSTOOLKIT_NORMALIZED_PROJECT_VERSION})
    set(PROJECT_VERSION_MAJOR ${_CSTOOLKIT_PROJECT_VERSION_MAJOR})
    set(PROJECT_VERSION_MINOR ${_CSTOOLKIT_PROJECT_VERSION_MINOR})
    set(PROJECT_VERSION_PATCH ${_CSTOOLKIT_PROJECT_VERSION_PATCH})
    set(PROJECT_VERSION_TWEAK ${_CSTOOLKIT_PROJECT_VERSION_TWEAK})
    set(PROJECT_VERSION_IDENTIFIER ${_CSTOOLKIT_PROJECT_VERSION_IDENTIFIER})

    set(${PROJECT_NAME}_VERSION ${_CSTOOLKIT_NORMALIZED_PROJECT_VERSION})
    set(${PROJECT_NAME}_VERSION_MAJOR ${_CSTOOLKIT_PROJECT_VERSION_MAJOR})
    set(${PROJECT_NAME}_VERSION_MINOR ${_CSTOOLKIT_PROJECT_VERSION_MINOR})
    set(${PROJECT_NAME}_VERSION_PATCH ${_CSTOOLKIT_PROJECT_VERSION_PATCH})
    set(${PROJECT_NAME}_VERSION_TWEAK ${_CSTOOLKIT_PROJECT_VERSION_TWEAK})
    set(${PROJECT_NAME}_VERSION_IDENTIFIER ${_CSTOOLKIT_PROJECT_VERSION_IDENTIFIER})
endif()
