if(DEFINED CSTOOLKIT_PROJECT_VERSION)
    set(CMAKE_PROJECT_VERSION ${CSTOOLKIT_PROJECT_VERSION} CACHE INTERNAL "Value Computed by CSToolkit")
    
    set(CMAKE_PROJECT_VERSION_MAJOR CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_MINOR CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_PATCH CACHE INTERNAL "Value Computed by CSToolkit")
    set(CMAKE_PROJECT_VERSION_TWEAK CACHE INTERNAL "Value Computed by CSToolkit")

    set(PROJECT_VERSION ${CSTOOLKIT_PROJECT_VERSION})
    set(${PROJECT_NAME}_VERSION ${CSTOOLKIT_PROJECT_VERSION})
endif()
