# Get the version from the git
if(CFMAKE_USE_GIT_TAG_VERSION)
    if(CFMAKE_GIT_TAG MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        set(CFMAKE_PROJECT_VERSION "${CFMAKE_GIT_TAG}")
        message(STATUS "Project version from git tag: ${CFMAKE_GIT_TAG}")
    elseif(CFMAKE_GIT_BRANCH MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        set(CFMAKE_PROJECT_VERSION "${CFMAKE_GIT_BRANCH}")
        message(STATUS "Project version set from branch: ${CFMAKE_GIT_BRANCH}")
    endif()
endif()

if(NOT CMAKE_PROJECT_VERSION OR
        NOT CFMAKE_PROJECT_VERSION STREQUAL "0.0.0.0")

    if(NOT CFMAKE_PROJECT_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?(-.+)?$")
        message(FATAL_ERROR "CFMake: Invalid format of CFMAKE_PROJECT_VERSION \"${CFMAKE_PROJECT_VERSION}\"")
    endif()

    string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?" _CFMAKE_NORMALIZED_PROJECT_VERSION "${CFMAKE_PROJECT_VERSION}")
    string(REGEX MATCH "-(.+)$" _CFMAKE_PROJECT_VERSION_IDENTIFIER "${CFMAKE_PROJECT_VERSION}")
    string(REGEX REPLACE "^-" "" _CFMAKE_PROJECT_VERSION_IDENTIFIER "${_CFMAKE_PROJECT_VERSION_IDENTIFIER}")

    string(REPLACE "." ";" _CFMAKE_PROJECT_VERSION_LIST ${_CFMAKE_NORMALIZED_PROJECT_VERSION})
    list(LENGTH _CFMAKE_PROJECT_VERSION_LIST _CFMAKE_PROJECT_VERSION_LENGTH)
    list(GET _CFMAKE_PROJECT_VERSION_LIST 0 _CFMAKE_PROJECT_VERSION_MAJOR)
    list(GET _CFMAKE_PROJECT_VERSION_LIST 1 _CFMAKE_PROJECT_VERSION_MINOR)
    list(GET _CFMAKE_PROJECT_VERSION_LIST 2 _CFMAKE_PROJECT_VERSION_PATCH)
    if(_CFMAKE_PROJECT_VERSION_LENGTH GREATER 3)
        list(GET _CFMAKE_PROJECT_VERSION_LIST 3 _CFMAKE_PROJECT_VERSION_TWEAK)
    endif()

    set(CMAKE_PROJECT_VERSION ${_CFMAKE_NORMALIZED_PROJECT_VERSION} CACHE INTERNAL "Value Computed by CFMake")
    # Because it is a static cache variable we have to set it as a internal cache then set it again as a local varaible
    set(CMAKE_PROJECT_VERSION ${_CFMAKE_NORMALIZED_PROJECT_VERSION})
    
    set(CMAKE_PROJECT_VERSION_MAJOR ${_CFMAKE_PROJECT_VERSION_MAJOR} CACHE INTERNAL "Value Computed by CFMake")
    set(CMAKE_PROJECT_VERSION_MINOR ${_CFMAKE_PROJECT_VERSION_MINOR} CACHE INTERNAL "Value Computed by CFMake")
    set(CMAKE_PROJECT_VERSION_PATCH ${_CFMAKE_PROJECT_VERSION_PATCH} CACHE INTERNAL "Value Computed by CFMake")
    set(CMAKE_PROJECT_VERSION_TWEAK ${_CFMAKE_PROJECT_VERSION_TWEAK} CACHE INTERNAL "Value Computed by CFMake")
    set(CMAKE_PROJECT_VERSION_IDENTIFIER ${_CFMAKE_PROJECT_VERSION_IDENTIFIER} CACHE INTERNAL "Value Computed by CFMake")
    # Because it is a static cache variable we have to set it as a internal cache then set it again as a local varaible
    set(CMAKE_PROJECT_VERSION_MAJOR ${_CFMAKE_PROJECT_VERSION_MAJOR})
    set(CMAKE_PROJECT_VERSION_MINOR ${_CFMAKE_PROJECT_VERSION_MINOR})
    set(CMAKE_PROJECT_VERSION_PATCH ${_CFMAKE_PROJECT_VERSION_PATCH})
    set(CMAKE_PROJECT_VERSION_TWEAK ${_CFMAKE_PROJECT_VERSION_TWEAK})
    set(CMAKE_PROJECT_VERSION_IDENTIFIER ${_CFMAKE_PROJECT_VERSION_IDENTIFIER})
    
    set(PROJECT_VERSION ${_CFMAKE_NORMALIZED_PROJECT_VERSION})
    set(PROJECT_VERSION_MAJOR ${_CFMAKE_PROJECT_VERSION_MAJOR})
    set(PROJECT_VERSION_MINOR ${_CFMAKE_PROJECT_VERSION_MINOR})
    set(PROJECT_VERSION_PATCH ${_CFMAKE_PROJECT_VERSION_PATCH})
    set(PROJECT_VERSION_TWEAK ${_CFMAKE_PROJECT_VERSION_TWEAK})
    set(PROJECT_VERSION_IDENTIFIER ${_CFMAKE_PROJECT_VERSION_IDENTIFIER})

    set(${PROJECT_NAME}_VERSION ${_CFMAKE_NORMALIZED_PROJECT_VERSION})
    set(${PROJECT_NAME}_VERSION_MAJOR ${_CFMAKE_PROJECT_VERSION_MAJOR})
    set(${PROJECT_NAME}_VERSION_MINOR ${_CFMAKE_PROJECT_VERSION_MINOR})
    set(${PROJECT_NAME}_VERSION_PATCH ${_CFMAKE_PROJECT_VERSION_PATCH})
    set(${PROJECT_NAME}_VERSION_TWEAK ${_CFMAKE_PROJECT_VERSION_TWEAK})
    set(${PROJECT_NAME}_VERSION_IDENTIFIER ${_CFMAKE_PROJECT_VERSION_IDENTIFIER})
endif()
