/*********************************************************************************
** Target informations object code generated by qmake {{QMAKE_VERSION}} ({{QT_VERSION}})
** WARNING! All changes made in this file will be lost when regenerating project!
**********************************************************************************/

#ifndef INFO_{{TARGET_INCGUARD}}_H
#define INFO_{{TARGET_INCGUARD}}_H
{{QT_APPLICATION}}
{{QT_LESS_THAN_5_1}}

    class QCoreApplication;
{{QT_LESS_THAN_5_1}}
{{QT_APPLICATION}}

namespace {{TARGET_NAMESPACE}} {


{{QT_APPLICATION}}
{{QT_LESS_THAN_5_1}}
    void setup( QCoreApplication * app );
    
{{QT_LESS_THAN_5_1}}
{{QT_APPLICATION}}
    const char * name();
    const char * version();
    const char * product();
    const char * organization();
    const char * copyright();
    
    
}

#endif