/*********************************************************************************
** Target informations object code generated by qmake {{QMAKE_VERSION}} ({{QT_VERSION}})
** WARNING! All changes made in this file will be lost when regenerating project!
**********************************************************************************/

#include "info_{{TARGET_INCLUDE}}.h"
{{QT_APPLICATION}}

#include <QCoreApplication>
#include <QLocale>
#include <QTextCodec>

namespace {


    void startup()
    {
        qApp->addLibraryPath( qApp->applicationDirPath() );
        
        qApp->setApplicationName( QString::fromUtf8( "{{TARGET_NAME}}" ) );
        qApp->setApplicationVersion( QString::fromUtf8( "{{TARGET_VERSION}}" ) );
        
        qApp->setOrganizationName( QString::fromUtf8( "{{TARGET_ORGANIZATION}}" ) );
        qApp->setOrganizationDomain( QString::fromUtf8( "{{TARGET_DOMAIN}}" ) );
        
        QLocale::setDefault( QLocale( QLocale::English, QLocale::UnitedStates ) );
        QTextCodec::setCodecForLocale( QTextCodec::codecForName( "UTF-8" ) );
    }
{{QT_GREATER_THAN_5_1}}

    Q_COREAPP_STARTUP_FUNCTION( startup )
{{QT_GREATER_THAN_5_1}}
    
    
}
{{QT_APPLICATION}}

namespace {{TARGET_NAMESPACE}} {


{{QT_APPLICATION}}
{{QT_LESS_THAN_5_1}}
    void setup( QCoreApplication * app )
    {
        if( app )
            startup();
    }
    
{{QT_LESS_THAN_5_1}}
{{QT_APPLICATION}}
    const char * name()
    {
        return "{{TARGET_NAME}}";
    }
    
    const char * version()
    {
        return "{{TARGET_VERSION}}";
    }
    
    const char * product()
    {
        return "{{TARGET_PRODUCT}}";
    }
    
    const char * organization()
    {
        return "{{TARGET_ORGANIZATION}}";
    }
    
    const char * copyright()
    {
        return "{{TARGET_COPYRIGHT}}";
    }
    
    
}
